title:             \Art '18
email:             your-email@example.com
description:       Check out what we're up to. 
author:            Christy Cui & Jacob Lee
baseurl:           "/backslashart.github.io"
url:               "http://backslashart-testing.github.io"

# Social Profiles
twitter_username:  none
github_username:   hyunjacoblee
facebook_username: none

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
